# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
# .github/workflows/python-tests.yml — matrix + modular extras
# ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

name: Python package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade pip (better resolver)
        run: python -m pip install --upgrade pip

      - name: Install environment
        run: |
          bash setup_env.sh

      - name: Run tests
        run: |
          source .venv/bin/activate
          .venv/bin/pytest -v

      # ─── Optional: install ML extras if needed ─────────
      # - name: Install ML extras
      #   run: bash setup_env.sh --ml
      #
      # - name: Run ML demos
      #   run: |
      #     source .venv/bin/activate
      #     python examples/ml_demo.py
